name: Criar Release Package

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Nome da tag para o novo release (ex: v1.0.0)'
        required: true
      release_name:
        description: 'Nome do release (ex: Vers√£o 1.0.0)'
        required: true
      prerelease:
        description: 'Marcar como pr√©-lan√ßamento?'
        required: false
        default: false
        type: boolean

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    # üëá Adicione estas linhas
    permissions:
      contents: write

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Criar pacote ZIP
        id: zip_repo
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'repo-package.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Criar Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          prerelease: ${{ github.event.inputs.prerelease }}
          artifacts: "repo-package.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
