name: Criar Release Package

# Define o evento para disparar o workflow manualmente pela interface do GitHub Actions
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Nome da tag para o novo release (ex: v1.0.0)'
        required: true
      release_name:
        description: 'Nome do release (ex: Versão 1.0.0)'
        required: true
      prerelease:
        description: 'Marcar como pré-lançamento?'
        required: false
        default: false
        type: boolean

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Compacta o repositório inteiro em um arquivo zip
      - name: Criar pacote ZIP
        id: zip_repo
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'repo-package.zip'
          # Exclui arquivos e diretórios desnecessários do zip
          exclusions: '*.git* /*node_modules/* .editorconfig'

      # Cria um novo release e anexa o pacote zip
      - name: Criar Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          prerelease: ${{ github.event.inputs.prerelease }}
          artifacts: "repo-package.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
